name: Build Kernel A52s SukiSU-Ultra
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Cai dat cong cu
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential git flex bison lz4 libssl-dev libelf-dev clang-14 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi binutils-aarch64-linux-gnu

      - name: 2. Tai ma nguon
        run: |
          git clone --depth=1 -b oneui-ksu https://github.com/JingMatrix/samsung_sm7325.git kernel

      - name: 3. Tich hop SukiSU-Ultra (Don rac SAU KHI cai)
        run: |
          cd kernel
          # B1: Cu cho no cai SukiSU-Ultra, ke no dung git stash hay gi
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s main
          
          # B2: Cai xong roi thi xoa chet cai dong code cu cua JingMatrix (xoa chinh xac tuyet doi)
          sed -i '/drivers\/kernelsu/d' drivers/Kconfig
          sed -i '/kernelsu\//d' drivers/Makefile

      - name: 4. Tien hanh nau Kernel
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang-14
          
          # Fix loi quet nham ban Han Quoc -> Chi quet dung ten a52sxq_defconfig
          CONFIG_FILE=$(find arch/arm64/configs -type f -name "a52sxq_defconfig" | head -n 1 | sed 's|arch/arm64/configs/||')
          echo "Da tim thay ban thiet ke quoc te xịn: $CONFIG_FILE"
          
          make O=out $CONFIG_FILE
          make O=out -j$(nproc)

      - name: 5. Dong goi file thanh pham
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-A52s-SukiSU-Ultra
          path: kernel/out/arch/arm64/boot/boot.img
